# Generated by Django 5.2.11 on 2026-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
